(lang dune 3.20)

(name task12_stack_machine)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name task12_stack_machine)
 (synopsis "Task 12: Toy Stack Machine and Compilation")
 (description "Learn to compile expressions to stack machine bytecode - the bridge to real VMs")
 (depends 
  ocaml
  dune
  alcotest)
 (tags
  ("ocaml" "learning" "compiler" "vm" "stack-machine" "bytecode")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
