(lang dune 3.20)

(name task10_constant_folding)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name task10_constant_folding)
 (synopsis "Task 10: Constant Folding and Algebraic Simplifications")
 (description "Learn AST transformations through constant folding and algebraic simplifications")
 (depends 
  ocaml
  dune
  alcotest)
 (tags
  ("ocaml" "learning" "compiler" "ast" "optimization")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
